<?php

namespace Database\Seeders;

use App\Models\Biaya;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class BiayaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            //registrasi hukum kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 1,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 1,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 1,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi hukum kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 1,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 1,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 1,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi hukum kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 1,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 1,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 1,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi hukum kelas B gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 2,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 2,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 2,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi hukum kelas B gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 2,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 2,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 2,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi hukum kelas B gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 2,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 2,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 2,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi manajemen kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 3,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 3,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 3,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi manajemen kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 3,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 3,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 3,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi manajemen kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 3,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 3,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 3,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi akutansi kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 4,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 4,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 4,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi akutansi kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 4,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 4,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 4,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi akutansi kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 4,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 4,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 4,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi mesin kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 5,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 5,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 5,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi mesin kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 5,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 5,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 5,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi mesin kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 5,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 5,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 5,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi mesin kelas B gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 6,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 6,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 6,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi mesin kelas B gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 6,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 6,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 6,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi mesin kelas B gelombang 1
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 6,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 6,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 6,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi sipil kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 7,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 7,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 7,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi sipil kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 7,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 7,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 7,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi sipil kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 7,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 7,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 7,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi sipil kelas B gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 8,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 8,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 8,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi sipil kelas B gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 8,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 8,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 8,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi sipil kelas B gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 8,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 8,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 8,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi A.Pendidikan kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 9,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 9,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 9,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi A.Pendidikan kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 9,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 9,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 9,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi A.Pendidikan kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 9,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 9,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 9,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi inggris kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 10,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 10,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 10,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi inggris kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 10,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 10,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 10,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi inggris kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 10,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 10,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 10,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi perawat kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 11,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 11,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi perawat kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 11,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 11,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi perawat kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 11,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 11,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi perawat kelas B gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 12,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi perawat kelas B gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 12,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi perawat kelas B gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 12,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi Ners kelas 1 gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 4,
                'kelas_id' => 13,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi Ners kelas 1 gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 4,
                'kelas_id' => 13,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi Ners kelas 1 gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 4,
                'kelas_id' => 13,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi Ners kelas 2 gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 4,
                'kelas_id' => 14,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi Ners kelas 2 gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 4,
                'kelas_id' => 14,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi Ners kelas 2 gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 4,
                'kelas_id' => 14,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi Ners kelas 3 gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 15,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi Ners kelas 3 gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 15,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi Ners kelas 3 gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 15,
                'kategori' => 'registrasi',
                'nominal' => 350000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],


            //registrasi M.Pendidikan kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 16,
                'kategori' => 'registrasi',
                'nominal' => 500000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi M.Pendidikan kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 16,
                'kategori' => 'registrasi',
                'nominal' => 500000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi M.Pendidikan kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 16,
                'kategori' => 'registrasi',
                'nominal' => 500000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //registrasi M.Pendidikan kelas B gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 17,
                'kategori' => 'registrasi',
                'nominal' => 500000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi M.Pendidikan kelas B gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 17,
                'kategori' => 'registrasi',
                'nominal' => 500000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //registrasi M.Pendidikan kelas B gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 17,
                'kategori' => 'registrasi',
                'nominal' => 500000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],








            // ------------------------------------------------------------------------------------------------
            /** Daftar ulang */
            //daftar_ulang hukum kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 1,
                'kategori' => 'daftar_ulang',
                'nominal' => 4070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 1,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 1,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang hukum kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 1,
                'kategori' => 'daftar_ulang',
                'nominal' => 4245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 1,
                'kategori' => 'daftar_ulang',
                'nominal' => 5245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 1,
                'kategori' => 'daftar_ulang',
                'nominal' => 5245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang hukum kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 1,
                'kategori' => 'daftar_ulang',
                'nominal' => 4420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 1,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 1,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang hukum kelas B gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 2,
                'kategori' => 'daftar_ulang',
                'nominal' => 4120000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 2,
                'kategori' => 'daftar_ulang',
                'nominal' => 5120000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 2,
                'kategori' => 'daftar_ulang',
                'nominal' => 5120000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang hukum kelas B gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 2,
                'kategori' => 'daftar_ulang',
                'nominal' => 4295000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 2,
                'kategori' => 'daftar_ulang',
                'nominal' => 5295000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 2,
                'kategori' => 'daftar_ulang',
                'nominal' => 5295000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang hukum kelas B gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 2,
                'kategori' => 'daftar_ulang',
                'nominal' => 4470000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 2,
                'kategori' => 'daftar_ulang',
                'nominal' => 5470000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 2,
                'kategori' => 'daftar_ulang',
                'nominal' => 5470000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang manajemen kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 3,
                'kategori' => 'daftar_ulang',
                'nominal' => 4070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 3,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 3,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang manajemen kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 3,
                'kategori' => 'daftar_ulang',
                'nominal' => 4245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 3,
                'kategori' => 'daftar_ulang',
                'nominal' => 5245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 3,
                'kategori' => 'daftar_ulang',
                'nominal' => 5245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang manajemen kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 3,
                'kategori' => 'daftar_ulang',
                'nominal' => 4420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 3,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 3,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang akutansi kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 4,
                'kategori' => 'daftar_ulang',
                'nominal' => 4070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 4,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 4,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang akutansi kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 4,
                'kategori' => 'daftar_ulang',
                'nominal' => 4245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 4,
                'kategori' => 'daftar_ulang',
                'nominal' => 5245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 4,
                'kategori' => 'daftar_ulang',
                'nominal' => 5245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang akutansi kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 4,
                'kategori' => 'daftar_ulang',
                'nominal' => 4420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 4,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 4,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang mesin kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 5,
                'kategori' => 'daftar_ulang',
                'nominal' => 4070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 5,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 5,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang mesin kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 5,
                'kategori' => 'daftar_ulang',
                'nominal' => 4245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 5,
                'kategori' => 'daftar_ulang',
                'nominal' => 5245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 5,
                'kategori' => 'daftar_ulang',
                'nominal' => 5245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang mesin kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 5,
                'kategori' => 'daftar_ulang',
                'nominal' => 4420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 5,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 5,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang mesin kelas B gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 6,
                'kategori' => 'daftar_ulang',
                'nominal' => 4120000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 6,
                'kategori' => 'daftar_ulang',
                'nominal' => 5120000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 6,
                'kategori' => 'daftar_ulang',
                'nominal' => 5120000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang mesin kelas B gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 6,
                'kategori' => 'daftar_ulang',
                'nominal' => 4295000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 6,
                'kategori' => 'daftar_ulang',
                'nominal' => 5295000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 6,
                'kategori' => 'daftar_ulang',
                'nominal' => 5295000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang mesin kelas B gelombang 1
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 6,
                'kategori' => 'daftar_ulang',
                'nominal' => 4470000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 6,
                'kategori' => 'daftar_ulang',
                'nominal' => 5470000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 6,
                'kategori' => 'daftar_ulang',
                'nominal' => 5470000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang sipil kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 7,
                'kategori' => 'daftar_ulang',
                'nominal' => 4070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 7,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 7,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang sipil kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 7,
                'kategori' => 'daftar_ulang',
                'nominal' => 4295000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 7,
                'kategori' => 'daftar_ulang',
                'nominal' => 5295000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 7,
                'kategori' => 'daftar_ulang',
                'nominal' => 5295000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang sipil kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 7,
                'kategori' => 'daftar_ulang',
                'nominal' => 4420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 7,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 7,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang sipil kelas B gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 8,
                'kategori' => 'daftar_ulang',
                'nominal' => 4120000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 8,
                'kategori' => 'daftar_ulang',
                'nominal' => 5120000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 8,
                'kategori' => 'daftar_ulang',
                'nominal' => 5120000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang sipil kelas B gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 8,
                'kategori' => 'daftar_ulang',
                'nominal' => 4295000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 8,
                'kategori' => 'daftar_ulang',
                'nominal' => 5295000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 8,
                'kategori' => 'daftar_ulang',
                'nominal' => 5295000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang sipil kelas B gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 8,
                'kategori' => 'daftar_ulang',
                'nominal' => 4470000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 8,
                'kategori' => 'daftar_ulang',
                'nominal' => 5470000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 8,
                'kategori' => 'daftar_ulang',
                'nominal' => 5470000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang A.Pendidikan kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 9,
                'kategori' => 'daftar_ulang',
                'nominal' => 4070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 9,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 9,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang A.Pendidikan kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 9,
                'kategori' => 'daftar_ulang',
                'nominal' => 4245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 9,
                'kategori' => 'daftar_ulang',
                'nominal' => 5245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 9,
                'kategori' => 'daftar_ulang',
                'nominal' => 5245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang A.Pendidikan kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 9,
                'kategori' => 'daftar_ulang',
                'nominal' => 4420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 9,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 9,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang inggris kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 10,
                'kategori' => 'daftar_ulang',
                'nominal' => 4070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 10,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 10,
                'kategori' => 'daftar_ulang',
                'nominal' => 5070000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang inggris kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 10,
                'kategori' => 'daftar_ulang',
                'nominal' => 4245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 10,
                'kategori' => 'daftar_ulang',
                'nominal' => 5245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 10,
                'kategori' => 'daftar_ulang',
                'nominal' => 5245000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang inggris kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 10,
                'kategori' => 'daftar_ulang',
                'nominal' => 4420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 10,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 10,
                'kategori' => 'daftar_ulang',
                'nominal' => 5420000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang perawat kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 11,
                'kategori' => 'daftar_ulang',
                'nominal' => 5825000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 3,
                'kelas_id' => 11,
                'kategori' => 'daftar_ulang',
                'nominal' => 6825000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang perawat kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 11,
                'kategori' => 'daftar_ulang',
                'nominal' => 5950000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 3,
                'kelas_id' => 11,
                'kategori' => 'daftar_ulang',
                'nominal' => 6950000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang perawat kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 11,
                'kategori' => 'daftar_ulang',
                'nominal' => 6075000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 3,
                'kelas_id' => 11,
                'kategori' => 'daftar_ulang',
                'nominal' => 7075000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang perawat kelas B gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 2,
                'kelas_id' => 12,
                'kategori' => 'daftar_ulang',
                'nominal' => 5525000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang perawat kelas B gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 2,
                'kelas_id' => 12,
                'kategori' => 'daftar_ulang',
                'nominal' => 5650000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang perawat kelas B gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 2,
                'kelas_id' => 12,
                'kategori' => 'daftar_ulang',
                'nominal' => 5775000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang Ners kelas 1 gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 4,
                'kelas_id' => 13,
                'kategori' => 'daftar_ulang',
                'nominal' => 2500000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang Ners kelas 1 gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 4,
                'kelas_id' => 13,
                'kategori' => 'daftar_ulang',
                'nominal' => 2500000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang Ners kelas 1 gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 4,
                'kelas_id' => 13,
                'kategori' => 'daftar_ulang',
                'nominal' => 2500000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang Ners kelas 2 gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 4,
                'kelas_id' => 14,
                'kategori' => 'daftar_ulang',
                'nominal' => 3600000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang Ners kelas 2 gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 4,
                'kelas_id' => 14,
                'kategori' => 'daftar_ulang',
                'nominal' => 3600000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang Ners kelas 2 gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 4,
                'kelas_id' => 14,
                'kategori' => 'daftar_ulang',
                'nominal' => 3600000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang Ners kelas 3 gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 15,
                'kategori' => 'daftar_ulang',
                'nominal' => 4600000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang Ners kelas 3 gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 15,
                'kategori' => 'daftar_ulang',
                'nominal' => 4600000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang Ners kelas 3 gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 15,
                'kategori' => 'daftar_ulang',
                'nominal' => 4600000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],


            //daftar_ulang M.Pendidikan kelas A gelombang 1
            [
                'gelombang_id' => 1,
                'jalur_masuk_id' => 1,
                'kelas_id' => 16,
                'kategori' => 'daftar_ulang',
                'nominal' => 3750000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang M.Pendidikan kelas A gelombang 2
            [
                'gelombang_id' => 2,
                'jalur_masuk_id' => 1,
                'kelas_id' => 16,
                'kategori' => 'daftar_ulang',
                'nominal' => 3750000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            //daftar_ulang M.Pendidikan kelas A gelombang 3
            [
                'gelombang_id' => 3,
                'jalur_masuk_id' => 1,
                'kelas_id' => 16,
                'kategori' => 'daftar_ulang',
                'nominal' => 3750000,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            //daftar_ulang M.Pendidikan kelas B gelombang 1 ( masih belum jelas )

        ];

        Biaya::insert($data);
    }
}
