<?php

namespace Database\Seeders;

use App\Models\JalurMasukKelas;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class JalurMasukKelasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // ToDo: Modifikasi variable data sesuai dengan model JalurMasukKelas
        // 'kelas_id', 'jalur_masuk_id', 'biaya_id', 'url'
        $data = [
            //kelas A hukum
            [
                'kelas_id' => 1,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 1,
                'jalur_masuk_id' => 2,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 1,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 1,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 1,
                'jalur_masuk_id' => 2,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 1,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 1,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 1,
                'jalur_masuk_id' => 2,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 1,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            //kelas B hukum
            [
                'kelas_id' => 2,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 2,
                'jalur_masuk_id' => 2,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 2,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 2,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 2,
                'jalur_masuk_id' => 2,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 2,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 2,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 2,
                'jalur_masuk_id' => 2,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 2,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //kelas A manajemen
            [
                'kelas_id' => 3,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 3,
                'jalur_masuk_id' => 2,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 3,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 3,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 3,
                'jalur_masuk_id' => 2,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 3,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 3,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 3,
                'jalur_masuk_id' => 2,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 3,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //kelas A akutansi
            [
                'kelas_id' => 4,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 4,
                'jalur_masuk_id' => 2,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 4,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 4,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 4,
                'jalur_masuk_id' => 2,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 4,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 4,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 4,
                'jalur_masuk_id' => 2,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 4,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //kelas A mesin
            [
                'kelas_id' => 5,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 5,
                'jalur_masuk_id' => 2,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 5,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 5,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 5,
                'jalur_masuk_id' => 2,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 5,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 5,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 5,
                'jalur_masuk_id' => 2,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 5,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //kelas B mesin
            [
                'kelas_id' => 6,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 6,
                'jalur_masuk_id' => 2,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 6,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 6,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 6,
                'jalur_masuk_id' => 2,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 6,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 6,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 6,
                'jalur_masuk_id' => 2,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 6,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //kelas A sipil
            [
                'kelas_id' => 7,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 7,
                'jalur_masuk_id' => 2,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 7,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 7,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 7,
                'jalur_masuk_id' => 2,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 7,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 7,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 7,
                'jalur_masuk_id' => 2,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 7,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //kelas B sipil
            [
                'kelas_id' => 8,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 8,
                'jalur_masuk_id' => 2,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 8,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 8,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 8,
                'jalur_masuk_id' => 2,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 8,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 8,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 8,
                'jalur_masuk_id' => 2,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 8,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //kelas A A.pendidikan
            [
                'kelas_id' => 9,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 9,
                'jalur_masuk_id' => 2,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 9,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 9,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 9,
                'jalur_masuk_id' => 2,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 9,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 9,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 9,
                'jalur_masuk_id' => 2,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 9,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //kelas A inggris
            [
                'kelas_id' => 10,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 10,
                'jalur_masuk_id' => 2,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 10,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 10,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 10,
                'jalur_masuk_id' => 2,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 10,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 10,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 10,
                'jalur_masuk_id' => 2,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 10,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //kelas A perawat
            [
                'kelas_id' => 11,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 11,
                'jalur_masuk_id' => 2,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 11,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 11,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 11,
                'jalur_masuk_id' => 2,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 11,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 11,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 11,
                'jalur_masuk_id' => 2,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 11,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //kelas B perawat
            [
                'kelas_id' => 12,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 12,
                'jalur_masuk_id' => 2,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 12,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 12,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 12,
                'jalur_masuk_id' => 2,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 12,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 12,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 12,
                'jalur_masuk_id' => 2,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 12,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //program 1 ners
            [
                'kelas_id' => 13,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 13,
                'jalur_masuk_id' => 4,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 13,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 13,
                'jalur_masuk_id' => 4,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 13,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 13,
                'jalur_masuk_id' => 4,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            //program 2 ners
            [
                'kelas_id' => 14,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 14,
                'jalur_masuk_id' => 4,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 14,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 14,
                'jalur_masuk_id' => 4,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 14,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 14,
                'jalur_masuk_id' => 4,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            //program 3 ners
            [
                'kelas_id' => 15,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 15,
                'jalur_masuk_id' => 4,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 15,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 15,
                'jalur_masuk_id' => 4,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 15,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 15,
                'jalur_masuk_id' => 4,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            //kelas A M.pendidikan
            [
                'kelas_id' => 16,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 16,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 16,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 16,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 16,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 16,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //kelas B M.pendidikan
            [
                'kelas_id' => 17,
                'jalur_masuk_id' => 1,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 17,
                'jalur_masuk_id' => 3,
                'biaya_id' => 1,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 17,
                'jalur_masuk_id' => 1,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 17,
                'jalur_masuk_id' => 3,
                'biaya_id' => 2,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 17,
                'jalur_masuk_id' => 1,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kelas_id' => 17,
                'jalur_masuk_id' => 3,
                'biaya_id' => 3,
                'url' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
        JalurMasukKelas::insert($data);
    }
}
